[package]
name = "pakedit"
version = "0.1.0"
authors = ["num0005 <double.null@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getset = "0.1.0"
text_io = "0.1.8"
console = "0.11.2"
shlex = "0.1.1"
